port: 7880
bind_addresses:
  - ""
rtc:
  port_range_start: 50000
  port_range_end: 50060
  tcp_port: 7881
  use_external_ip: true
keys:
  API43c72f0f0e6338a3: LNEjm4LVgldaaI4142uRYavT_SGCxaz21uPa_MLBYAs
logging:
  level: info
turn:
  enabled: true
  udp_port: 3478
