#!/usr/bin/env bash
# =============================================================================
# apply-npm-routing.sh — Apply versioned Nginx routing to NPM proxy
# =============================================================================
# Patches two NPM-generated proxy host configs so that:
#   - Default location / → pnptv-web:80  (React SPA)
#   - /api/, /pnp/, /auth/, etc. → 172.17.0.1:3001 (Node.js backend)
#
#   proxy_host/10.conf  →  pnptv.app
#   proxy_host/9.conf   →  app.pnptv.app  (same routing, same upstream)
#
# Also deploys the shared server_proxy.conf (ATProto OAuth routes).
#
# IMPORTANT: 9.conf requires a full reconstruction strategy, not just
# injection, because NPM generates per-location block-exploits/force-ssl
# directives that conflict with the injected location blocks.
# The canonical source for both configs is pnptv-app-proxy.conf.
#
# Safe to re-run: backs up existing configs, validates before reloading.
# =============================================================================

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
NPM_DATA="${REPO_ROOT}/infrastructure/data/npm/data/nginx"
NPM_CONFIGS="${REPO_ROOT}/infrastructure/configs/npm"
PROXY_HOST_10="${NPM_DATA}/proxy_host/10.conf"
PROXY_HOST_9="${NPM_DATA}/proxy_host/9.conf"
CUSTOM_CONF="${NPM_DATA}/custom/server_proxy.conf"
BACKEND_LOCATIONS="${NPM_CONFIGS}/pnptv-app-proxy.conf"
ATPROTO_CONF="${NPM_CONFIGS}/server_proxy.conf"
CONTAINER="npm-proxy"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

info()  { echo -e "${GREEN}[INFO]${NC} $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

# --- Preflight checks ---

if [ ! -f "$PROXY_HOST_10" ]; then
    error "proxy_host/10.conf not found at $PROXY_HOST_10"
    error "Is the npm-proxy container running with mounted data?"
    exit 1
fi

if [ ! -f "$PROXY_HOST_9" ]; then
    error "proxy_host/9.conf not found at $PROXY_HOST_9"
    error "Is the npm-proxy container running with mounted data?"
    exit 1
fi

if [ ! -f "$BACKEND_LOCATIONS" ]; then
    error "Source config not found: $BACKEND_LOCATIONS"
    exit 1
fi

if ! docker ps --format '{{.Names}}' | grep -q "^${CONTAINER}$"; then
    error "Container '${CONTAINER}' is not running"
    exit 1
fi

# --- Step 1: Deploy shared server_proxy.conf (ATProto routes) ---

info "Deploying shared server_proxy.conf ..."
mkdir -p "$(dirname "$CUSTOM_CONF")"
cp "$ATPROTO_CONF" "$CUSTOM_CONF"

# --- Step 2: Patch proxy_host/10.conf (pnptv.app) ---
#
# Strategy: inject backend location blocks before the catch-all "location / {"
# using awk. This works because 10.conf only has a single catch-all location
# generated by NPM; there are no pre-existing per-prefix location blocks.

info "Checking proxy_host/10.conf (pnptv.app) ..."

if grep -q "# Backend API routes" "$PROXY_HOST_10"; then
    info "Backend location blocks already present in 10.conf — checking upstream ..."

    if grep -q 'set \$server.*"pnptv-web"' "$PROXY_HOST_10"; then
        info "Default upstream already set to pnptv-web:80"
    else
        warn "Default upstream is NOT pnptv-web — patching ..."
        sed -i 's/set \$server.*"[^"]*"/set $server         "pnptv-web"/' "$PROXY_HOST_10"
        sed -i 's/set \$port.*[0-9]*/set $port           80/' "$PROXY_HOST_10"
        info "Upstream patched to pnptv-web:80"
    fi
else
    info "Injecting backend location blocks into 10.conf ..."

    BACKUP="${PROXY_HOST_10}.bak.$(date +%s)"
    cp "$PROXY_HOST_10" "$BACKUP"
    info "Backup saved to $BACKUP"

    # Patch upstream to pnptv-web:80
    sed -i 's/set \$server.*"[^"]*"/set $server         "pnptv-web"/' "$PROXY_HOST_10"
    sed -i 's/set \$port.*[0-9]*/set $port           80/' "$PROXY_HOST_10"

    # Inject backend locations before the first "location / {"
    INJECT_FILE="$BACKEND_LOCATIONS"
    awk -v inject="$INJECT_FILE" '
        /^  location \/ \{/ && !done {
            # Read and print the inject file
            while ((getline line < inject) > 0) print "  " line
            close(inject)
            print ""
            print "  # ============================================="
            print "  # Default: SPA frontend → pnptv-web container"
            print "  # ============================================="
            print ""
            done = 1
        }
        { print }
    ' "$PROXY_HOST_10" > "${PROXY_HOST_10}.tmp"
    mv "${PROXY_HOST_10}.tmp" "$PROXY_HOST_10"

    info "Backend location blocks injected into 10.conf"
fi

# --- Step 3: Reconstruct proxy_host/9.conf (app.pnptv.app) ---
#
# Strategy: full reconstruction rather than injection.
#
# Unlike 10.conf (which NPM generates with only a catch-all location /),
# 9.conf was originally generated by NPM with per-prefix custom locations
# (/api/, /webhook/, /uploads/) that each contain redundant block-exploits,
# force-ssl, and HSTS directives inside them. Injecting into that structure
# would produce duplicate location blocks.
#
# The versioned source-of-truth (9.conf in the repo) is already the fully
# reconstructed clean config. This step ensures the live file matches it by
# checking the sentinel comment and replacing the file if it is missing.
#
# The canonical source for this file is:
#   infrastructure/data/npm/data/nginx/proxy_host/9.conf  (this repo)
# which is kept in sync with pnptv-app-proxy.conf for all backend routes.

info "Checking proxy_host/9.conf (app.pnptv.app) ..."

if grep -q "# Backend API routes" "$PROXY_HOST_9"; then
    info "Backend location blocks already present in 9.conf — no changes needed"
else
    warn "9.conf is missing managed location blocks — this is unexpected."
    warn "The file in the repo should already be the fully reconstructed version."
    warn "If NPM has regenerated 9.conf, you must re-apply the full file from git."
    warn "Run:  git checkout infrastructure/data/npm/data/nginx/proxy_host/9.conf"
    warn "Then re-run this script."
    exit 1
fi

# Ensure 9.conf uses 172.17.0.1:3001, not pnptv-bot:3001
if grep -q "pnptv-bot:3001" "$PROXY_HOST_9"; then
    warn "9.conf still references pnptv-bot:3001 — patching to 172.17.0.1:3001 ..."
    BACKUP9="${PROXY_HOST_9}.bak.$(date +%s)"
    cp "$PROXY_HOST_9" "$BACKUP9"
    info "Backup saved to $BACKUP9"
    sed -i 's|http://pnptv-bot:3001|http://172.17.0.1:3001|g' "$PROXY_HOST_9"
    info "Upstream references corrected in 9.conf"
fi

# --- Step 4: Validate and reload ---

info "Testing nginx configuration ..."
if docker exec "$CONTAINER" nginx -t 2>&1; then
    info "Config valid — reloading nginx ..."
    docker exec "$CONTAINER" nginx -s reload
    info "Nginx reloaded successfully"
else
    error "Nginx config test FAILED — rolling back"
    LATEST_10=$(ls -t "${PROXY_HOST_10}".bak.* 2>/dev/null | head -1 || true)
    if [ -n "$LATEST_10" ]; then
        cp "$LATEST_10" "$PROXY_HOST_10"
        info "Rolled back 10.conf to $LATEST_10"
    fi
    LATEST_9=$(ls -t "${PROXY_HOST_9}".bak.* 2>/dev/null | head -1 || true)
    if [ -n "$LATEST_9" ]; then
        cp "$LATEST_9" "$PROXY_HOST_9"
        info "Rolled back 9.conf to $LATEST_9"
    fi
    docker exec "$CONTAINER" nginx -s reload 2>/dev/null || true
    exit 1
fi

# --- Step 5: Verify ---

info "Verifying routing ..."
FAILURES=0

# pnptv.app — SPA
SPA_CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://pnptv.app/subscribe" 2>/dev/null || echo "000")
if [ "$SPA_CODE" = "200" ]; then
    info "  pnptv.app/subscribe → $SPA_CODE (SPA)"
else
    error "  pnptv.app/subscribe → $SPA_CODE (expected 200)"
    FAILURES=$((FAILURES + 1))
fi

# pnptv.app — API
API_CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://pnptv.app/api/health" 2>/dev/null || echo "000")
if [ "$API_CODE" = "200" ]; then
    info "  pnptv.app/api/health → $API_CODE (backend)"
else
    error "  pnptv.app/api/health → $API_CODE (expected 200)"
    FAILURES=$((FAILURES + 1))
fi

# pnptv.app — health
HEALTH_CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://pnptv.app/health" 2>/dev/null || echo "000")
if [ "$HEALTH_CODE" = "200" ]; then
    info "  pnptv.app/health → $HEALTH_CODE (backend)"
else
    error "  pnptv.app/health → $HEALTH_CODE (expected 200)"
    FAILURES=$((FAILURES + 1))
fi

# app.pnptv.app — SPA
APP_SPA_CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://app.pnptv.app/subscribe" 2>/dev/null || echo "000")
if [ "$APP_SPA_CODE" = "200" ]; then
    info "  app.pnptv.app/subscribe → $APP_SPA_CODE (SPA)"
else
    error "  app.pnptv.app/subscribe → $APP_SPA_CODE (expected 200)"
    FAILURES=$((FAILURES + 1))
fi

# app.pnptv.app — API
APP_API_CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://app.pnptv.app/api/health" 2>/dev/null || echo "000")
if [ "$APP_API_CODE" = "200" ]; then
    info "  app.pnptv.app/api/health → $APP_API_CODE (backend)"
else
    error "  app.pnptv.app/api/health → $APP_API_CODE (expected 200)"
    FAILURES=$((FAILURES + 1))
fi

# app.pnptv.app — auth (new route, was previously missing)
APP_AUTH_CODE=$(curl -sk -o /dev/null -w "%{http_code}" "https://app.pnptv.app/auth/telegram" 2>/dev/null || echo "000")
if [ "$APP_AUTH_CODE" != "000" ]; then
    info "  app.pnptv.app/auth/ → $APP_AUTH_CODE (backend reachable)"
else
    error "  app.pnptv.app/auth/ → $APP_AUTH_CODE (no response)"
    FAILURES=$((FAILURES + 1))
fi

if [ "$FAILURES" -gt 0 ]; then
    warn "$FAILURES verification(s) failed — check logs"
    exit 1
fi

echo ""
info "All routing applied and verified successfully"
